#!/usr/bin/env bash
# displays information about subdomains.


get_dns_info() {
    if [ -z "$2" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$2")
    fi

    for sub in "${subdomains[@]}"; do
        dns_info=$(dig $sub.$1 | grep -A1 'ANSWER SECTION' | tail -1)
        record_type=$(echo "$dns_info" | awk '{print $4}')
        destination=$(echo "$dns_info" | awk '{print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_dns_info "$1" "$2"
