#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server/a\\
	location /redirect_me {\\
		return 301 https://github.com/5XGeorgeX5;\\
	}" /etc/nginx/sites-available/default
service nginx restart
