#!/usr/bin/env bash
# change the port from 8080 to port 80.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
