#!/usr/bin/env bash
# displays the content of the file /etc/passwd


while read -r line
do
    print=$(echo "$line" | cut -d ':' -f 1)
    print2=$(echo "$line" | cut -d ':' -f 3)
    print3=$(echo "$line" | cut -d ':' -f 6)
    echo "$print:$print2:$print3"
done < /etc/passwd
