#!/usr/bin/env bash
# displays the content of the file /etc/passwd


while IFS=':' read -r USER PASSWORD USER_ID GROUP_ID INFO HOME SHELL
do
    echo "The user $USER is part of the $GROUP_ID gang, lives in $HOME and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < /etc/passwd
